# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-04-22 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_clientbank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientbank',
            name='user',
        ),
    ]
